# Generated by Django 2.1.5 on 2019-01-17 18:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EthnicityLookup',
            fields=[
                ('id', models.IntegerField(max_length=4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='GenderLookup',
            fields=[
                ('id', models.IntegerField(max_length=4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='GradeYearLookup',
            fields=[
                ('id', models.IntegerField(max_length=4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.CharField(max_length=60, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Demographic',
            fields=[
                ('id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='api.Student')),
                ('age', models.IntegerField(max_length=2)),
                ('ethnicity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.EthnicityLookup')),
                ('gender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.GenderLookup')),
                ('grade_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.GradeYearLookup')),
            ],
        ),
        migrations.AddField(
            model_name='student',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
