# Generated by Django 2.1.5 on 2019-03-04 21:54

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('95093536-ab80-4adf-a9d0-031087f57d25'), editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50)),
                ('semester', models.CharField(choices=[('FL', 'Fall'), ('SP', 'Spring'), ('SM', 'Summer')], default='FL', max_length=2)),
                ('year', models.IntegerField(default=2019)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('title',),
                'verbose_name_plural': 'Classes',
            },
        ),
        migrations.CreateModel(
            name='ClassEnrollment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_enrolled', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Class')),
            ],
            options={
                'verbose_name_plural': 'Class Enrollments',
            },
        ),
        migrations.CreateModel(
            name='DayLookup',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=10)),
            ],
            options={
                'verbose_name_plural': 'Days',
            },
        ),
        migrations.CreateModel(
            name='Demographic',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('2dd666ab-61f9-4de2-8b1c-0f1f2542cada'), editable=False, primary_key=True, serialize=False)),
                ('age', models.IntegerField()),
                ('major', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='EthnicityLookup',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='GenderLookup',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='GradeYearLookup',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('7219f0af-43b1-43bf-af27-3a581b8520fd'), editable=False, primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(default=datetime.datetime(2019, 3, 4, 21, 54, 39, 225332, tzinfo=utc))),
                ('x', models.FloatField()),
                ('y', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='RaceLookup',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('85b14248-7f52-4cef-a1e0-66d94faa5030'), editable=False, primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(default=datetime.datetime(2019, 3, 4, 21, 54, 39, 78689, tzinfo=utc), editable=False)),
                ('expires', models.DateTimeField(default=datetime.datetime(2019, 3, 5, 21, 54, 39, 222338, tzinfo=utc))),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('reset_password_code', models.CharField(blank=True, max_length=6, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='position',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Student'),
        ),
        migrations.AddField(
            model_name='demographic',
            name='ethnicity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.EthnicityLookup'),
        ),
        migrations.AddField(
            model_name='demographic',
            name='gender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.GenderLookup'),
        ),
        migrations.AddField(
            model_name='demographic',
            name='grade_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.GradeYearLookup'),
        ),
        migrations.AddField(
            model_name='demographic',
            name='race',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.RaceLookup'),
        ),
        migrations.AddField(
            model_name='demographic',
            name='student',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.Student'),
        ),
        migrations.AddField(
            model_name='classenrollment',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Student'),
        ),
        migrations.AddField(
            model_name='class',
            name='days_of_the_week',
            field=models.ManyToManyField(to='api.DayLookup'),
        ),
        migrations.AddField(
            model_name='class',
            name='students',
            field=models.ManyToManyField(to='api.Student'),
        ),
        migrations.AlterUniqueTogether(
            name='classenrollment',
            unique_together={('student', 'class_enrolled')},
        ),
        migrations.AlterUniqueTogether(
            name='class',
            unique_together={('title', 'semester', 'year')},
        ),
    ]
