# Generated by Django 2.1.5 on 2019-01-17 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demographic',
            name='age',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='ethnicitylookup',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='genderlookup',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='gradeyearlookup',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
