# Generated by Django 2.1.5 on 2019-03-23 17:53

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('cd34ef75-d205-44cf-838f-97ec9fff5959'), editable=False, primary_key=True, serialize=False)),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SurveyQuestion',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('45c7a4b7-1e3f-412d-9b1b-7542767f77fc'), editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('SA', 'Short Answer'), ('LA', 'Essay'), ('RA', 'Range')], default='SA', max_length=2)),
                ('prompt_text', models.TextField()),
                ('survey', models.ForeignKey(on_delete=None, to='api.Survey')),
            ],
        ),
        migrations.CreateModel(
            name='SurveyResponse',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('0ff96844-e278-4906-98d8-cb01566d2261'), editable=False, primary_key=True, serialize=False)),
                ('response', models.TextField()),
                ('surveyQuestion', models.ForeignKey(on_delete=None, to='api.SurveyQuestion')),
            ],
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ('user__last_name', 'user__first_name')},
        ),
        migrations.AddField(
            model_name='class',
            name='section',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='class',
            name='id',
            field=models.UUIDField(default=uuid.UUID('eb0f2e31-ca4a-4252-99c7-502b4aa46662'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='class',
            name='students',
            field=models.ManyToManyField(default=None, null=True, to='api.Student'),
        ),
        migrations.AlterField(
            model_name='demographic',
            name='id',
            field=models.UUIDField(default=uuid.UUID('f921ecf2-c42a-420e-88b2-059167e41ec4'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='position',
            name='id',
            field=models.UUIDField(default=uuid.UUID('f74cfec2-2f02-46e6-be96-186f972e1e76'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='position',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 23, 17, 53, 11, 501109, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='session',
            name='expires',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 24, 17, 53, 11, 498127, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='session',
            name='id',
            field=models.UUIDField(default=uuid.UUID('142364b7-7469-4383-b0f9-88d9038684d3'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='session',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 23, 17, 53, 11, 348517, tzinfo=utc), editable=False),
        ),
        migrations.AddField(
            model_name='survey',
            name='associated_class',
            field=models.ForeignKey(on_delete=None, to='api.Class'),
        ),
    ]
