# Generated by Django 2.1.5 on 2019-03-23 17:58

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_Survey_Models'),
    ]

    operations = [
        migrations.AddField(
            model_name='surveyresponse',
            name='student',
            field=models.ForeignKey(default='4c2d28e5-fe76-4d3a-802a-c5605103c905', on_delete=None, to='api.Student'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='class',
            name='id',
            field=models.UUIDField(default=uuid.UUID('e81e2106-b403-421d-bae9-2e949d457401'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='demographic',
            name='id',
            field=models.UUIDField(default=uuid.UUID('cd25a4f4-4fce-486b-8a65-b1c9d70570e6'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='position',
            name='id',
            field=models.UUIDField(default=uuid.UUID('db7e16b5-979c-4e5d-acf4-6ab520faa942'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='position',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 23, 17, 58, 25, 299357, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='session',
            name='expires',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 24, 17, 58, 25, 297363, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='session',
            name='id',
            field=models.UUIDField(default=uuid.UUID('55e4d77f-6b03-4c5e-a6cd-99688b47508c'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='session',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 23, 17, 58, 25, 150719, tzinfo=utc), editable=False),
        ),
        migrations.AlterField(
            model_name='survey',
            name='id',
            field=models.UUIDField(default=uuid.UUID('41f9d66a-1f7f-42ec-88ba-19eb47fbe3c6'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='surveyquestion',
            name='id',
            field=models.UUIDField(default=uuid.UUID('675cd175-32ce-4ca7-a76a-fc99ef38513b'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='surveyresponse',
            name='id',
            field=models.UUIDField(default=uuid.UUID('a7895a4d-7842-4819-b150-4cbad70d5c98'), editable=False, primary_key=True, serialize=False),
        ),
    ]
