# Generated by Django 2.1.7 on 2019-04-02 18:55

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0002_Make_Survey_Instance_Models'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='session',
            name='expires',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 3, 18, 55, 17, 472263, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='session',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AlterField(
            model_name='surveyresponse',
            name='survey_entry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.SurveyEntryInstance'),
        ),
        migrations.AlterUniqueTogether(
            name='survey',
            unique_together={('admin', 'associated_class')},
        ),
    ]
