# Generated by Django 2.1.5 on 2019-01-18 02:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20190117_2059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='api.Student'),
        ),
    ]
