# Generated by Django 2.1.5 on 2019-03-24 22:56

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_Add Student to Survey Response'),
    ]

    operations = [
        migrations.RenameField(
            model_name='surveyresponse',
            old_name='surveyQuestion',
            new_name='survey_question',
        ),
        migrations.RemoveField(
            model_name='class',
            name='students',
        ),
        migrations.AlterField(
            model_name='class',
            name='id',
            field=models.UUIDField(default=uuid.UUID('2fd8fe43-def6-4624-b9c3-a8632f16b4af'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='demographic',
            name='id',
            field=models.UUIDField(default=uuid.UUID('ea40bc0e-9e29-4d03-a353-3ee2363f1b59'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='position',
            name='id',
            field=models.UUIDField(default=uuid.UUID('825c4b40-678a-47b5-8c7a-eef0d74dd565'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='position',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 24, 22, 56, 42, 903038, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='session',
            name='expires',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 25, 22, 56, 42, 901046, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='session',
            name='id',
            field=models.UUIDField(default=uuid.UUID('5afc2d72-c4c7-4de7-888e-65144c88d150'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='session',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 24, 22, 56, 42, 801310, tzinfo=utc), editable=False),
        ),
        migrations.AlterField(
            model_name='survey',
            name='id',
            field=models.UUIDField(default=uuid.UUID('c33814a1-35f4-4b18-9942-22636ff48765'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='surveyquestion',
            name='id',
            field=models.UUIDField(default=uuid.UUID('c5424e36-968d-431e-b0b1-11752f1bab32'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='surveyresponse',
            name='id',
            field=models.UUIDField(default=uuid.UUID('754d0162-9d6b-432d-b064-d1e0dbfc8d2d'), editable=False, primary_key=True, serialize=False),
        ),
    ]
