# Generated by Django 2.1.7 on 2019-04-03 06:50

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_Change_Survey_Instance_Models'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='expires',
        ),
        migrations.RemoveField(
            model_name='surveyresponse',
            name='student',
        ),
        migrations.AddField(
            model_name='surveyinstance',
            name='student',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='api.Student'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='surveyinstance',
            name='date_generated',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
