# Generated by Django 2.1.7 on 2019-03-26 01:35

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_Change SurveyResponse Question FK'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('57697e37-1ea8-43ce-8127-67ddfe5578a0'), editable=False, primary_key=True, serialize=False)),
                ('feedback', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='class',
            name='id',
            field=models.UUIDField(default=uuid.UUID('d45f4c04-ff02-4f73-bc64-cb5b54bbb2df'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='demographic',
            name='id',
            field=models.UUIDField(default=uuid.UUID('5b40da0f-f01f-4d30-be8a-928d235250e1'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='position',
            name='id',
            field=models.UUIDField(default=uuid.UUID('070cc4c7-66dc-431b-be7c-eb6afc9228e3'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='position',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 26, 1, 35, 4, 117619, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='session',
            name='expires',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 27, 1, 35, 4, 114626, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='session',
            name='id',
            field=models.UUIDField(default=uuid.UUID('c01c679d-da05-49d1-91a7-d728fceb68f4'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='session',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 26, 1, 35, 3, 960057, tzinfo=utc), editable=False),
        ),
        migrations.AlterField(
            model_name='survey',
            name='id',
            field=models.UUIDField(default=uuid.UUID('91b01fa1-353a-4c53-b52b-858be8b92215'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='surveyquestion',
            name='id',
            field=models.UUIDField(default=uuid.UUID('96851816-3fb0-43a6-9a71-800cbd06dda4'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='surveyresponse',
            name='id',
            field=models.UUIDField(default=uuid.UUID('dce3fd89-4a66-411d-b2c3-b343ed7f58ca'), editable=False, primary_key=True, serialize=False),
        ),
    ]
