# Generated by Django 2.1.5 on 2019-01-18 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20190117_2107'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='reset_password_code',
            field=models.UUIDField(default='a67ba7d4-03aa-4554-85e6-6d01d0925f20'),
            preserve_default=False,
        ),
    ]
