# Generated by Django 2.1.5 on 2019-01-18 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_student_reset_password_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='reset_password_code',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
