# Generated by Django 2.1.5 on 2019-01-18 14:14

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20190117_2327'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='student',
            field=models.ForeignKey(default='bf8a0b7a-a13f-4590-8241-364b7fb3a65c', on_delete=django.db.models.deletion.CASCADE, to='api.Student'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='position',
            name='id',
            field=models.UUIDField(default=uuid.UUID('d2634d57-c48c-46cf-a319-f293ae8a4e9d'), editable=False, primary_key=True, serialize=False),
        ),
    ]
