# Generated by Django 2.1.5 on 2019-01-22 17:48

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20190118_0914'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='id',
            field=models.UUIDField(default=uuid.UUID('d4ec2352-75cd-4e3c-8eaf-edd5c02b677b'), editable=False, primary_key=True, serialize=False),
        ),
    ]
