# Generated by Django 2.1.5 on 2019-01-24 17:37

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20190122_1248'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='reset_code_expiration',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='position',
            name='id',
            field=models.UUIDField(default=uuid.UUID('2d60136b-f99a-4235-9873-60e5047a81d8'), editable=False, primary_key=True, serialize=False),
        ),
    ]
