# Generated by Django 2.1.5 on 2019-02-02 14:26

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_auto_20190124_1402'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demographic',
            name='id',
            field=models.UUIDField(default=uuid.UUID('493c737a-4036-4eb5-8ada-da573347918c'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='position',
            name='id',
            field=models.UUIDField(default=uuid.UUID('401b4a1f-a4b1-4e96-9871-cb723b68bba2'), editable=False, primary_key=True, serialize=False),
        ),
    ]
