# Generated by Django 2.1.5 on 2019-02-02 14:28

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_auto_20190202_0926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demographic',
            name='id',
            field=models.UUIDField(default=uuid.UUID('b4706f43-179d-4a0c-b99e-1a0a75a1274f'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='position',
            name='id',
            field=models.UUIDField(default=uuid.UUID('1fe9dd37-00ca-4908-bddc-dcfb8d046a47'), editable=False, primary_key=True, serialize=False),
        ),
    ]
