# Generated by Django 2.1.5 on 2019-02-02 14:29

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_auto_20190202_0928'),
    ]

    operations = [
        migrations.AddField(
            model_name='demographic',
            name='student',
            field=models.OneToOneField(default='bf8a0b7a-a13f-4590-8241-364b7fb3a65c', on_delete=django.db.models.deletion.CASCADE, to='api.Student'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='demographic',
            name='id',
            field=models.UUIDField(default=uuid.UUID('076ddb77-b921-486a-82c2-207c1426a11b'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='position',
            name='id',
            field=models.UUIDField(default=uuid.UUID('faa49c05-280b-43ee-a76b-3b9b525dee12'), editable=False, primary_key=True, serialize=False),
        ),
    ]
