# Generated by Django 2.1.5 on 2019-02-02 15:02

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_auto_20190202_0929'),
    ]

    operations = [
        migrations.AddField(
            model_name='demographic',
            name='major',
            field=models.CharField(default='None', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='demographic',
            name='id',
            field=models.UUIDField(default=uuid.UUID('f96510c0-1de5-46ca-901f-23b83dfeda44'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='position',
            name='id',
            field=models.UUIDField(default=uuid.UUID('1a870cd8-3673-4e4f-ad87-4315419a70fa'), editable=False, primary_key=True, serialize=False),
        ),
    ]
