# Generated by Django 2.1.5 on 2019-02-05 15:04

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_auto_20190205_1003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='id',
            field=models.UUIDField(default=uuid.UUID('632d142d-9648-44d2-a05c-5d98bec62e5b'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='demographic',
            name='id',
            field=models.UUIDField(default=uuid.UUID('bcbb3715-650a-4240-8737-36258f442d91'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='position',
            name='id',
            field=models.UUIDField(default=uuid.UUID('5af8dc63-cd29-4587-b38c-a5f91b6d4605'), editable=False, primary_key=True, serialize=False),
        ),
    ]
