# Generated by Django 2.1.5 on 2019-02-05 15:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_auto_20190205_1012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='admin',
            field=models.ForeignKey(default=6, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='class',
            name='id',
            field=models.UUIDField(default=uuid.UUID('e7c8371a-fad6-4bc9-8ed5-34bf4efbe0f4'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='demographic',
            name='id',
            field=models.UUIDField(default=uuid.UUID('6c5de98a-d6ac-45dc-881d-1c3bd824518e'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='position',
            name='id',
            field=models.UUIDField(default=uuid.UUID('97137f00-65b7-4760-b87c-063bd7048c8d'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterUniqueTogether(
            name='classenrollment',
            unique_together={('student', 'class_enrolled')},
        ),
    ]
