# Generated by Django 2.1.5 on 2019-02-05 15:27

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_auto_20190205_1022'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='semester',
            field=models.CharField(choices=[('FL', 'Fall'), ('SP', 'Spring'), ('SM', 'Summer')], default='FL', max_length=2),
        ),
        migrations.AddField(
            model_name='class',
            name='year',
            field=models.IntegerField(default=2019),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='class',
            name='id',
            field=models.UUIDField(default=uuid.UUID('a5b2b2ce-45d3-43bb-831d-1d72b26f4c18'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='demographic',
            name='id',
            field=models.UUIDField(default=uuid.UUID('35130116-ebe0-42c1-9c21-e5cd4282a579'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='position',
            name='id',
            field=models.UUIDField(default=uuid.UUID('aba11526-dadc-44de-ba75-ed74dd1a503b'), editable=False, primary_key=True, serialize=False),
        ),
    ]
