# Generated by Django 2.1.5 on 2019-02-14 17:45

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_auto_20190205_1027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='id',
            field=models.UUIDField(default=uuid.UUID('d148a2d7-2d8e-462b-9232-91766cf9ce73'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='class',
            name='year',
            field=models.IntegerField(default=2019),
        ),
        migrations.AlterField(
            model_name='demographic',
            name='id',
            field=models.UUIDField(default=uuid.UUID('7bca88c2-20eb-4f4b-8f46-1c27d3875118'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='position',
            name='id',
            field=models.UUIDField(default=uuid.UUID('2da028c7-59ae-4096-ba25-42a9f2a1b83b'), editable=False, primary_key=True, serialize=False),
        ),
    ]
